name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Get tooling
      run: |
        go get golang.org/x/lint/golint
        go get honnef.co/go/tools/cmd/staticcheck

    - name: Run build
      run: go build -v -tags=gofuzz ./...

    - name: Run vet
      run: go vet ./...

    - name: Run staticcheck
      run: staticcheck ./...

    - name: Run lint
      run: golint -set_exit_status ./cmd/... ./internal/...

    - name: Run test
      run: go test -v -race ./...
